local   all             all                                     trust
hostssl all             all             all                     scram-sha-256 clientcert=verify-full
hostnossl all           all             all                     reject
