services:

  policy-engine:
    build: ./policy-engine
    image: policy-engine:latest
    container_name: policy-engine
    ports:
      - "8080:8080"
    networks:
      - control_net
      - frontend_net
      - siem_net
    depends_on:
      - asset-db
      - idp-oidc
      - splunk
    environment:
      - TRUST_THRESHOLD=105
      - SERVICE_NAME=policy-engine
      - SIEM_URL=http://splunk:8088
    volumes:
      - ./internal-certs:/etc/service-certs

  idp-oidc:
    build: ./idp-oidc
    image: idp-oidc:latest
    container_name: idp-oidc
    ports:
      - "8081:8081"
    networks:
      - control_net
      - siem_net
    depends_on:
      - asset-db
      - splunk
    environment:
      - ASSET_DB_HOST=asset-db
      - ASSET_DB_PORT=5432
      - ASSET_DB_USER=postgres
      - ASSET_DB_PASSWORD=postgres
      - ASSET_DB_NAME=postgres
      - SERVICE_NAME=idp-oidc
      - SIEM_URL=http://splunk:8088

  asset-db:
    image: postgres:15-alpine
    container_name: asset-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./asset-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - control_net

  web-server-pep:
    image: nginx:latest
    container_name: web-server-pep
    networks:
      - frontend_net
    ports:
      - "443:443"
    volumes:
      - ./web-server-pep/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-server-pep/html:/usr/share/nginx/html:ro
      - ./web-server-pep/certs:/etc/nginx/certs:ro
      - ./internal-certs:/etc/nginx/internal-certs:ro
    depends_on:
      - policy-engine
      - app-service

  app-service:
    build: ./app-service
    image: app-service:latest
    container_name: app-service
    ports:
      - "8000:8000"
    depends_on:
      - secure-db
      - splunk
    environment:
      - SECURE_DB_HOST=secure-db
      - SECURE_DB_PORT=5432
      - SECURE_DB_USER=postgres
      - SECURE_DB_PASSWORD=postgres
      - SECURE_DB_NAME=postgres
      - SECURE_DB_SSLROOTCERT=/etc/service-certs/ca.pem
      - SECURE_DB_SSLCERT=/etc/service-certs/app-db-client.crt
      - SECURE_DB_SSLKEY=/etc/service-certs/app-db-client.key
      - APP_TLS_CA_CERTS=/etc/service-certs/ca.pem
      - APP_TLS_CERTFILE=/etc/service-certs/app-service.crt
      - APP_TLS_KEYFILE=/etc/service-certs/app-service.key
      - SERVICE_NAME=app-service
      - SIEM_URL=http://splunk:8088
    networks:
      - backend_net
      - frontend_net
      - siem_net
    volumes:
      - ./internal-certs:/etc/service-certs

  secure-db:
    build:
      context: .
      dockerfile: secure-db/Dockerfile
    image: secure-db:latest
    container_name: secure-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./secure-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend_net

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      # Username = Admin
      - SPLUNK_PASSWORD=Admin1234!
      - SPLUNK_HEC_TOKEN=security-hec-token
      - SPLUNK_HEC_SSL=false
    ports:
      - "8001:8000"
    volumes:
      - ./splunk/zta_security:/opt/splunk/etc/apps/zta_security
    networks:
      - siem_net
      - frontend_net

networks:
  control_net:
    internal: true
  frontend_net:
  backend_net:
    internal: true
  siem_net:
    internal: true
